# Generated by Django 3.2.8 on 2021-11-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_list_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='username',
            new_name='user',
        ),
    ]
