# Generated by Django 3.2.8 on 2021-11-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_list_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='type',
            field=models.CharField(blank=True, choices=[('Movie', 'Movie'), ('TV', 'TV')], max_length=5),
        ),
    ]
