# Generated by Django 3.2.8 on 2021-11-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_list_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.CharField(choices=[('Watching', 'Watching'), ('Plan to watch', 'Plan to watch'), ('Completed', 'Completed'), ('On hold', 'On hold')], max_length=20),
        ),
    ]
