# Generated by Django 3.2.8 on 2021-11-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_list_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
