# Generated by Django 3.2.8 on 2021-11-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_list_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='favourite',
            new_name='favorite',
        ),
    ]
